### ISSUE TITLE
Analysis checklist

### ISSUE THREAD

**Issue by jklymak** [kurtisanstey/project#1]
## Ways to average:

- [x] example year (2013)
- [x] years averaged to get an average season cycle

## frequency bands:
- [x] sub-diurnal 
- [x] diurnal
- [x] near-inertial 
- [x] Semidiurnal
- [x] continuum

## energy sources:

- [x] wind
- [x] tides
- [x] CTWs

**Comment by kurtisanstey** [comment]
Updates to be referenced in soon-to-be linked Analysis document.

**Comment by kurtisanstey** [comment]
Updated Analysis document. Need to gather seasonal observations into categories (as listed, above).

**Comment by kurtisanstey** [comment]
Hi Kurtis,

This document is looking great.  There is *lots* here.  

This is a mishmash of comments, but if you work your way through them I think you will make some progress.  But balance dealing with the smaller thinsg wtih making progress on other fronts.

Thanks!  Jody

# Kurtis Analysis Doc thoughts  15 Jan 2021

- put the map in here?  
- please refer to figure numbers.  I can't tell what figures you are talking about in your description.  
- cite actual papers I don't know what `A1 data (Thompson)` means.  Set up your Bibtex file now and start using it!

## Upper slope 75 kHz.

### mean currents: 
- I'm surprised they are mostly northwards.  
- do they really compare well with A1?  
- what are all the pretty big mean changes?  Are those real?  If so, what causes them?  Maybe not a focus, particulary if Rick has seen them, but it would help making believability to show that he saw them, and we saw them and then a couple of sentences in the thesis about what is happening.  
- I like your noting the 2-week periodicity and its seasonality.  A spring-neap cycle modulates the tides, which are positive and negative.  Spring-neap is S2+M2, and does not show up as a 14-d frequency in the spectrogram.  Is that what you are talking about, or are you talking about the low-frequency current modulating on 2-week time scales?  Again, is this something Rick already talks about?  

### high-passed:
- 2014 looks funny in the high pass?  Maybe just aliasing in the plotting?  You probably need to do something different if you are going to plot the residuals like this.  Hard to see much, and hard to tell that its not aliased.  Zoomed in this is useful, for a whole year, probably not.  For a whole year, you may want to instead plot |u|, with some smoothing (maybe a couple of days?)  This will show spring neap cycles.  

## Axis:

- Are the bursts of positive mean currents, ie.. 2017, above 600 m, correlated with the slope mean currents?  
- high-pass same as above, either these are aliased to create banding or this is not a proper high pass.  Look at 2017 - why would a high-pass have long time periods of blue, and then high time periods of red?  If that is real when you zoom in, then you've done your band passing incorrectly.  If its aliasing due to plotting, we can't plot that way.  
- As discussed, we can't fill over such long gaps.  Please leave blank


- Fig 3 is nice, but the aliasing is still a problem.  

Over all the velocity plots are "fine" for looking at mean currents.  They don't say anything about internal waves the way they are plotted, so if we see sometjimhg we want to highlight in the internal wave field we will have to come up with some way to highlight that.  Idea above is probably as good as any.  A pcolor of variance integrated between 1.2*M2 and Nyquist might also work.  

Slope:  Annual PSDs look nice.  I agree w/ your observations.  Looks like there is no significant inter annual variability, which is good.  Some differences in the low frequencies.  Similarly rotary spectra look great.  Note the rotary and normal spectra tell complimentary information here, so its kinda useful to have both.  You may consider showing them together rather than spread apart over sections.  Seasonal: is it true that they have similar amplitudes?  I guess the changes are subtle, but there are differences.  Interesting the deep data at the slope seems to have weaker internal waves in the summer, but the near-surface data stays the same?  Bit hard to tell. 

- something to do w/ the spectra is to fit a power law to the continuum range.  Slope looks pretty consistent, and less steep than f^{-2}.   I assume other people have seen that, but what do they see?  

Axis:  Annual PSDs look good 2017 and 2018, but with a significantly higher noise floor than the 75 Khz (though the shallow data suffers from bad data).  Very interesting that all the wave bands are higher at depth than at 400 m.  Again, has that been seen before?   Curious that along-slope variability is so high at sub-inertial frequencies even at the deep location.  I guess that goes to whether the along-canyon flow is the same as the broad shelf flow.  

- I'd check why the 55 kHz noise floor is so much higher.  I wonder if they are not averaging pings or something.  

Interesting that there is no near-inertial peak in the canyon.  

CW/CCW almost the same in deep canyon.  Presumably canyon-rectified flows?  Seems there is a deep K1 signal.  Could be shelf waves, or signal in the canyon?  

Spectrograms: what is your time resolution on the x axis?   Is there aliasing in these?  

Seasonal: Best to line up w/ spring neap cycles?  Maybe need to change color limits for these.    

- Did you scale by N^2 for the spectra?  

- Do we think the spec grams are telling us much?  It looks to me that there are times when the internal waves broadband goes up and down on pretty short time scales, which would actually be quite interesting  (i.e. Fig 13c).  But I'm not sure if that is real or some sort of aliasing.

**Comment by kurtisanstey** [comment]
Need to reorganise this issue into relevant components as analysis progresses.

**Comment by kurtisanstey** [comment]
These have all been checked, specific analysis now in relevant issue updates.
